#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    p = arr[-1]
    for ind in range(len(arr)-2, -1, -1):
        if arr[ind] > p:
            arr[ind+1] = arr[ind]
            print(" ".join(map(str, arr)))
        else:
            arr[ind+1] = p
            print(" ".join(map(str, arr)))
            break
    if arr[0] > p:
        arr[0] = p
        print(" ".join(map(str, arr)))
        
    # Write your code here

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
